-- Todo — Supabase setup. Run once in the SQL Editor. Safe to re-run.
--
-- Everything lives in a dedicated "todo" schema so this instance can be shared
-- with other small projects. To remove this app entirely:  drop schema todo cascade;
--
-- AFTER RUNNING THIS: add "todo" under Settings -> API -> Exposed schemas.
-- PostgREST only serves schemas listed there; without it every request 404s.

create schema if not exists todo;

-- ---------- Grants ----------
-- Supabase grants these automatically for "public" but not for custom schemas.

grant usage on schema todo to anon, authenticated, service_role;
grant all on all tables    in schema todo to anon, authenticated, service_role;
grant all on all sequences in schema todo to anon, authenticated, service_role;
grant all on all routines  in schema todo to anon, authenticated, service_role;

alter default privileges in schema todo grant all on tables    to anon, authenticated, service_role;
alter default privileges in schema todo grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema todo grant all on routines  to anon, authenticated, service_role;

-- ---------- Tables ----------
-- Ids are generated by the client (crypto.randomUUID) and reused verbatim here,
-- so a mirror pass is a plain upsert with no id mapping to maintain.

create table if not exists todo.folders (
  id          uuid primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name        text not null,
  position    integer not null default 0,
  updated_at  timestamptz not null default now()
);

create table if not exists todo.categories (
  id          uuid primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  folder_id   uuid not null references todo.folders(id) on delete cascade,
  name        text not null,
  position    integer not null default 0,
  updated_at  timestamptz not null default now()
);

create table if not exists todo.tasks (
  id            uuid primary key,
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  folder_id     uuid not null references todo.folders(id) on delete cascade,
  category_id   uuid not null references todo.categories(id) on delete cascade,
  subject       text not null default '',
  description   text not null default '',
  completed     boolean not null default false,
  important     boolean not null default false,
  due_date      date,
  position      integer not null default 0,
  created_at    timestamptz not null default now(),
  completed_at  timestamptz,
  updated_at    timestamptz not null default now()
);

create index if not exists folders_user_pos    on todo.folders    (user_id, position);
create index if not exists categories_fold_pos on todo.categories (folder_id, position);
create index if not exists tasks_cat_pos       on todo.tasks      (category_id, position);
create index if not exists tasks_user          on todo.tasks      (user_id);

-- ---------- updated_at ----------
-- Set server-side so a row's mtime can't be faked by a client with a skewed
-- clock. Useful later for deciding which side of a two-device edit is newer.

create or replace function todo.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists folders_touch    on todo.folders;
drop trigger if exists categories_touch on todo.categories;
drop trigger if exists tasks_touch      on todo.tasks;

create trigger folders_touch    before update on todo.folders    for each row execute function todo.touch_updated_at();
create trigger categories_touch before update on todo.categories for each row execute function todo.touch_updated_at();
create trigger tasks_touch      before update on todo.tasks      for each row execute function todo.touch_updated_at();

-- ---------- Row Level Security ----------
-- The publishable key is public by design and lives in a public repo, so RLS is
-- the only thing protecting this data. An unauthenticated caller gets auth.uid()
-- = NULL, which matches no row and permits no insert.

alter table todo.folders    enable row level security;
alter table todo.categories enable row level security;
alter table todo.tasks      enable row level security;

drop policy if exists folders_owner    on todo.folders;
drop policy if exists categories_owner on todo.categories;
drop policy if exists tasks_owner      on todo.tasks;

create policy folders_owner    on todo.folders    for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy categories_owner on todo.categories for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy tasks_owner      on todo.tasks      for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------- Realtime ----------
-- Not needed while one machine is the source of truth; harmless to enable now
-- so a second device later is a client change only. The publication is shared
-- with every other project on this instance, hence the membership check.

do $$
declare t text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
  foreach t in array array['folders', 'categories', 'tasks'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'todo' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table todo.%I', t);
    end if;
  end loop;
end $$;

-- ---------- Storage bucket for pasted images ----------
-- Buckets are global to the instance, so the name is project-prefixed.
-- Private: files are reachable only through short-lived signed URLs.

insert into storage.buckets (id, name, public)
  values ('todo-images', 'todo-images', false)
  on conflict (id) do nothing;

-- These policies live on the shared storage.objects table alongside every
-- other project's, hence the project-prefixed names. Each user can only touch
-- files under their own uid, which is the path prefix the app uploads to.

drop policy if exists todo_images_select on storage.objects;
drop policy if exists todo_images_insert on storage.objects;
drop policy if exists todo_images_update on storage.objects;
drop policy if exists todo_images_delete on storage.objects;

create policy todo_images_select on storage.objects for select
  using  (bucket_id = 'todo-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy todo_images_insert on storage.objects for insert
  with check (bucket_id = 'todo-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy todo_images_update on storage.objects for update
  using  (bucket_id = 'todo-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy todo_images_delete on storage.objects for delete
  using  (bucket_id = 'todo-images' and (storage.foldername(name))[1] = auth.uid()::text);
